"""empty message

Revision ID: 11e899993f3a
Revises: 0ce0b68c292a
Create Date: 2020-12-16 00:16:33.800704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e899993f3a'
down_revision = '0ce0b68c292a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reservation', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'reservation', type_='unique')
    # ### end Alembic commands ###
