"""empty message

Revision ID: 460d5afabcc1
Revises: ac2c3950a44b
Create Date: 2020-12-15 23:58:33.579358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460d5afabcc1'
down_revision = 'ac2c3950a44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reservation_roomID_fkey', 'reservation', type_='foreignkey')
    op.create_unique_constraint(None, 'space', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'space', type_='unique')
    op.create_foreign_key('reservation_roomID_fkey', 'reservation', 'space', ['roomID'], ['id'])
    # ### end Alembic commands ###
