"""empty message

Revision ID: 769c1cd47617
Revises: c405de9ea978
Create Date: 2020-12-15 18:52:39.324495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769c1cd47617'
down_revision = 'c405de9ea978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'reservationTime',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'reservationTime',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
