"""empty message

Revision ID: f35d8e23a483
Revises: e96e177d8c0a
Create Date: 2020-12-15 17:03:51.917675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f35d8e23a483'
down_revision = 'e96e177d8c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('is_reserved', sa.Boolean(), nullable=True))
    op.add_column('reservation', sa.Column('reservationTime', sa.Integer(), nullable=False))
    op.add_column('reservation', sa.Column('roomID', sa.Integer(), nullable=False))
    op.drop_constraint('reservation_user_id_fkey', 'reservation', type_='foreignkey')
    op.create_foreign_key(None, 'reservation', 'space', ['roomID'], ['id'])
    op.drop_column('reservation', 'is_publish')
    op.drop_column('reservation', 'user_id')
    op.add_column('space', sa.Column('is_reserved', sa.Boolean(), nullable=True))
    op.add_column('space', sa.Column('reservableTimes', sa.ARRAY(sa.String()), nullable=True))
    op.drop_constraint('space_user_id_fkey', 'space', type_='foreignkey')
    op.drop_column('space', 'is_publish')
    op.drop_column('space', 'user_id')
    op.drop_column('space', 'reservable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('reservable', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('space', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('space', sa.Column('is_publish', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('space_user_id_fkey', 'space', 'user', ['user_id'], ['id'])
    op.drop_column('space', 'reservableTimes')
    op.drop_column('space', 'is_reserved')
    op.add_column('reservation', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reservation', sa.Column('is_publish', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.create_foreign_key('reservation_user_id_fkey', 'reservation', 'user', ['user_id'], ['id'])
    op.drop_column('reservation', 'roomID')
    op.drop_column('reservation', 'reservationTime')
    op.drop_column('reservation', 'is_reserved')
    # ### end Alembic commands ###
